# Generated by Django 4.1.4 on 2022-12-28 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='tweet',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Mark',
        ),
    ]
